#!/usr/bin/env python3
"""MIG sampling stage (decoupled from scoring).

Input should be generated by `mig.py` and contain at least:
- id
- labels (or mig_labels)
- score (scalar quality)
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import zlib
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Tuple

import numpy as np

try:
    from sentence_transformers import SentenceTransformer
except Exception:  # noqa: BLE001
    SentenceTransformer = None


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class DataPoint:
    labels: List[str]
    score: float
    raw: Dict[str, Any]


def load_json_or_jsonl(path: str) -> Tuple[List[Dict[str, Any]], str]:
    with open(path, "r", encoding="utf-8") as f:
        text = f.read().strip()

    if not text:
        return [], "jsonl"

    try:
        data = json.loads(text)
        if isinstance(data, list):
            return data, "json"
        raise ValueError("Input JSON must be a list of objects.")
    except json.JSONDecodeError:
        lines = [line for line in text.splitlines() if line.strip()]
        return [json.loads(line) for line in lines], "jsonl"


def write_json_or_jsonl(path: str, rows: List[Dict[str, Any]], prefer_jsonl: bool) -> None:
    out_dir = os.path.dirname(path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    output_is_jsonl = prefer_jsonl or path.lower().endswith(".jsonl")
    with open(path, "w", encoding="utf-8") as f:
        if output_is_jsonl:
            for row in rows:
                f.write(json.dumps(row, ensure_ascii=False) + "\n")
        else:
            json.dump(rows, f, ensure_ascii=False, indent=2)


def dedup_keep_order(items: Iterable[str]) -> List[str]:
    out: List[str] = []
    seen = set()
    for item in items:
        k = str(item).strip()
        if not k or k in seen:
            continue
        seen.add(k)
        out.append(k)
    return out


def to_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:  # noqa: BLE001
        return default


def _hash_embed_one(text: str, dim: int = 384) -> np.ndarray:
    vec = np.zeros(dim, dtype=np.float32)
    s = f" {str(text).lower().strip()} "
    if not s.strip():
        return vec

    grams: List[str] = []
    if len(s) >= 3:
        grams = [s[i : i + 3] for i in range(len(s) - 2)]
    else:
        grams = [s]

    for gram in grams:
        idx = zlib.crc32(gram.encode("utf-8")) % dim
        vec[idx] += 1.0

    n = float(np.linalg.norm(vec))
    if n > 0:
        vec /= n
    return vec


def encode_texts(
    texts: List[str],
    *,
    embedding_backend: str,
    embedding_model: str,
    embedding_cache: str,
) -> Tuple[np.ndarray, str]:
    if not texts:
        return np.zeros((0, 0), dtype=np.float32), "empty"

    backend = embedding_backend.strip().lower()
    if backend not in {"auto", "sentence_transformers", "hash"}:
        raise ValueError("--embedding_backend must be one of: auto, sentence_transformers, hash")

    if backend in {"auto", "sentence_transformers"}:
        if SentenceTransformer is None:
            if backend == "sentence_transformers":
                raise ModuleNotFoundError(
                    "sentence-transformers is not installed. Install it or use --embedding_backend hash"
                )
            logger.warning("sentence-transformers unavailable, fallback to hash embeddings.")
        else:
            try:
                cache = embedding_cache.strip() or None
                model_name = embedding_model.strip() or "sentence-transformers/all-MiniLM-L6-v2"
                model = SentenceTransformer(model_name, cache_folder=cache)
                arr = model.encode(
                    texts,
                    normalize_embeddings=True,
                    convert_to_numpy=True,
                    show_progress_bar=False,
                )
                arr = np.asarray(arr, dtype=np.float32)
                if arr.ndim != 2:
                    raise ValueError(f"Unexpected embedding shape: {arr.shape}")
                return arr, "sentence_transformers"
            except Exception as exc:  # noqa: BLE001
                if backend == "sentence_transformers":
                    raise
                logger.warning("sentence-transformers encode failed (%s), fallback to hash embeddings.", exc)

    emb = np.stack([_hash_embed_one(t) for t in texts], axis=0)
    return emb, "hash"


def build_label_graph_wam(
    labels: List[str],
    *,
    sim_threshold: float,
    embedding_backend: str,
    embedding_model: str,
    embedding_cache: str,
) -> Tuple[np.ndarray, str]:
    if not labels:
        return np.zeros((0, 0), dtype=np.float32), "empty"

    emb, backend_used = encode_texts(
        labels,
        embedding_backend=embedding_backend,
        embedding_model=embedding_model,
        embedding_cache=embedding_cache,
    )
    x = np.asarray(emb, dtype=np.float32)
    n = np.linalg.norm(x, axis=1, keepdims=True)
    n = np.maximum(n, 1e-12)
    x = x / n

    sim = x @ x.T
    sim = np.clip(sim, -1.0, 1.0)
    wam = np.where(sim >= float(sim_threshold), sim, 0.0).astype(np.float32)
    return wam, backend_used


def d_phi(x: np.ndarray, phi_type: str, phi_alpha: float, phi_a: float, phi_b: float) -> np.ndarray:
    if phi_type == "exp":
        return float(phi_alpha) * np.exp(-float(phi_alpha) * x)
    if phi_type == "pow":
        return float(phi_b) * np.power(x + float(phi_a), float(phi_b) - 1.0)
    raise ValueError(f"Invalid phi_type: {phi_type}")


def calc_prop_matrix(wam: np.ndarray, prop_weight: float) -> np.ndarray:
    if wam.size == 0:
        return wam

    n = wam.shape[0]
    eye = np.eye(n, dtype=np.float32)
    p_diag = wam * eye
    p_ndiag = wam * (1.0 - eye) * float(prop_weight)
    p = p_diag + p_ndiag

    col_sum = p.sum(axis=0, keepdims=True)
    col_sum = np.where(col_sum <= 1e-12, 1.0, col_sum)
    p = p / col_sum
    return p.astype(np.float32)


def vectorize_dataset(
    dataset: List[DataPoint],
    label_to_index: Dict[str, int],
    *,
    norm: bool,
) -> np.ndarray:
    vec = np.zeros((len(dataset), len(label_to_index)), dtype=np.float32)
    for i, dp in enumerate(dataset):
        labels = [x for x in dp.labels if x in label_to_index]
        n_labels = len(labels)
        if n_labels == 0:
            continue
        v = float(dp.score) if not norm else float(dp.score) / float(n_labels)
        for label in labels:
            j = label_to_index[label]
            vec[i, j] = v
    return vec


def sample_mig(
    dataset: List[DataPoint],
    *,
    num_sample: int,
    sim_threshold: float,
    phi_type: str,
    phi_alpha: float,
    phi_a: float,
    phi_b: float,
    prop_weight: float,
    norm: bool,
    batch_size: int,
    embedding_backend: str,
    embedding_model: str,
    embedding_cache: str,
) -> Tuple[List[int], Dict[str, Any]]:
    n_data = len(dataset)
    if n_data == 0 or num_sample <= 0:
        return [], {"num_labels": 0, "embedding_backend": "empty"}

    num_sample = min(int(num_sample), n_data)

    labels = sorted({label for dp in dataset for label in dp.labels if label})
    label_to_index = {label: i for i, label in enumerate(labels)}

    if not labels:
        # No labels at all: fallback to descending score.
        order = sorted(range(n_data), key=lambda i: float(dataset[i].score), reverse=True)
        return order[:num_sample], {"num_labels": 0, "embedding_backend": "empty"}

    wam, backend_used = build_label_graph_wam(
        labels,
        sim_threshold=sim_threshold,
        embedding_backend=embedding_backend,
        embedding_model=embedding_model,
        embedding_cache=embedding_cache,
    )
    mat_p = calc_prop_matrix(wam, prop_weight=prop_weight)
    vec_pool = vectorize_dataset(dataset, label_to_index, norm=norm)
    vec_pool_prop = vec_pool @ mat_p

    mask = np.ones(n_data, dtype=bool)
    vec_x_sel = np.zeros((len(labels),), dtype=np.float32)
    selected: List[int] = []

    for _ in range(num_sample):
        vec_g = d_phi(vec_x_sel, phi_type=phi_type, phi_alpha=phi_alpha, phi_a=phi_a, phi_b=phi_b)

        remain_indices = np.flatnonzero(mask)
        if remain_indices.size == 0:
            break

        if batch_size and batch_size > 0:
            best_idx = int(remain_indices[0])
            best_score = float("-inf")
            for start in range(0, remain_indices.size, int(batch_size)):
                chunk = remain_indices[start : start + int(batch_size)]
                cand = vec_pool_prop[chunk] @ vec_g
                local_argmax = int(np.argmax(cand))
                local_score = float(cand[local_argmax])
                if local_score > best_score:
                    best_score = local_score
                    best_idx = int(chunk[local_argmax])
        else:
            cand = vec_pool_prop[remain_indices] @ vec_g
            best_local = int(np.argmax(cand))
            best_idx = int(remain_indices[best_local])

        selected.append(best_idx)
        vec_x_sel += vec_pool_prop[best_idx]
        mask[best_idx] = False

    meta = {
        "num_labels": len(labels),
        "embedding_backend": backend_used,
        "label_list": labels,
    }
    return selected, meta


def parse_score_row(row: Dict[str, Any]) -> DataPoint | None:
    labels_raw = row.get("labels", row.get("mig_labels", row.get("instag_tags", [])))
    labels: List[str] = []
    if isinstance(labels_raw, list):
        labels = dedup_keep_order(str(x).strip() for x in labels_raw if str(x).strip())

    score_val = row.get("score", row.get("delta_scalar", 0.0))
    if isinstance(score_val, list):
        score = float(sum(to_float(x, 0.0) for x in score_val))
    else:
        score = to_float(score_val, 0.0)

    return DataPoint(labels=labels, score=score, raw=row)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="MIG sampling stage (reads scored file from mig.py).")
    parser.add_argument("--scored_path", type=str, required=True, help="MIG score file path from mig.py")
    parser.add_argument("--output_path", type=str, required=True, help="Sampled output path")
    parser.add_argument("--num_samples", type=int, required=True, help="Target number of samples")

    parser.add_argument("--sim_threshold", type=float, default=0.9, help="Label graph similarity threshold")
    parser.add_argument("--phi_type", type=str, default="pow", choices=["pow", "exp"])
    parser.add_argument("--phi_alpha", type=float, default=1.0)
    parser.add_argument("--phi_a", type=float, default=1e-6)
    parser.add_argument("--phi_b", type=float, default=0.8)
    parser.add_argument("--prop_weight", type=float, default=1.0)
    parser.add_argument(
        "--norm",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Whether to normalize point score by number of labels when vectorizing.",
    )
    parser.add_argument("--batch_size", type=int, default=0)

    parser.add_argument(
        "--embedding_backend",
        type=str,
        default="auto",
        choices=["auto", "sentence_transformers", "hash"],
    )
    parser.add_argument(
        "--embedding_model",
        type=str,
        default="sentence-transformers/all-MiniLM-L6-v2",
    )
    parser.add_argument("--embedding_cache", type=str, default="")

    parser.add_argument(
        "--meta_output_path",
        type=str,
        default="",
        help="Optional path to save label-graph metadata and selected indices.",
    )
    parser.add_argument(
        "--include_rank",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Whether to append mig_selected_rank to each sampled row.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    scored_rows, scored_fmt = load_json_or_jsonl(args.scored_path)
    logger.info("Loaded scored rows=%d from %s", len(scored_rows), args.scored_path)

    dataset: List[DataPoint] = []
    for row in scored_rows:
        dp = parse_score_row(row)
        if dp is None:
            continue
        dataset.append(dp)

    selected_indices, meta = sample_mig(
        dataset,
        num_sample=int(args.num_samples),
        sim_threshold=float(args.sim_threshold),
        phi_type=args.phi_type,
        phi_alpha=float(args.phi_alpha),
        phi_a=float(args.phi_a),
        phi_b=float(args.phi_b),
        prop_weight=float(args.prop_weight),
        norm=bool(args.norm),
        batch_size=int(args.batch_size),
        embedding_backend=args.embedding_backend,
        embedding_model=args.embedding_model,
        embedding_cache=args.embedding_cache,
    )

    sampled_rows: List[Dict[str, Any]] = []
    for rank, idx in enumerate(selected_indices):
        row = dict(dataset[idx].raw)
        if args.include_rank:
            row["mig_selected_rank"] = rank
        sampled_rows.append(row)

    write_json_or_jsonl(args.output_path, sampled_rows, prefer_jsonl=(scored_fmt == "jsonl"))
    logger.info(
        "Saved MIG sampled rows=%d (target=%d) to %s",
        len(sampled_rows),
        int(args.num_samples),
        args.output_path,
    )

    if args.meta_output_path:
        out_dir = os.path.dirname(args.meta_output_path)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)

        payload = {
            "num_input_rows": len(dataset),
            "num_sampled_rows": len(sampled_rows),
            "target_num_samples": int(args.num_samples),
            "sim_threshold": float(args.sim_threshold),
            "phi_type": args.phi_type,
            "phi_alpha": float(args.phi_alpha),
            "phi_a": float(args.phi_a),
            "phi_b": float(args.phi_b),
            "prop_weight": float(args.prop_weight),
            "norm": bool(args.norm),
            "batch_size": int(args.batch_size),
            "selected_indices": selected_indices,
            **meta,
        }
        with open(args.meta_output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
        logger.info("Saved MIG sampling meta to %s", args.meta_output_path)


if __name__ == "__main__":
    main()
